<?php
declare(strict_types=1);

// Fastcon SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

FastconUtility::setRegistrar(function (FastconUtility $u): void {
    $u->clean = [FastconClean::class, 'call'];
    $u->done = [FastconDone::class, 'call'];
    $u->make_error = [FastconMakeError::class, 'call'];
    $u->feature_add = [FastconFeatureAdd::class, 'call'];
    $u->feature_hook = [FastconFeatureHook::class, 'call'];
    $u->feature_init = [FastconFeatureInit::class, 'call'];
    $u->fetcher = [FastconFetcher::class, 'call'];
    $u->make_fetch_def = [FastconMakeFetchDef::class, 'call'];
    $u->make_context = [FastconMakeContext::class, 'call'];
    $u->make_options = [FastconMakeOptions::class, 'call'];
    $u->make_request = [FastconMakeRequest::class, 'call'];
    $u->make_response = [FastconMakeResponse::class, 'call'];
    $u->make_result = [FastconMakeResult::class, 'call'];
    $u->make_point = [FastconMakePoint::class, 'call'];
    $u->make_spec = [FastconMakeSpec::class, 'call'];
    $u->make_url = [FastconMakeUrl::class, 'call'];
    $u->param = [FastconParam::class, 'call'];
    $u->prepare_auth = [FastconPrepareAuth::class, 'call'];
    $u->prepare_body = [FastconPrepareBody::class, 'call'];
    $u->prepare_headers = [FastconPrepareHeaders::class, 'call'];
    $u->prepare_method = [FastconPrepareMethod::class, 'call'];
    $u->prepare_params = [FastconPrepareParams::class, 'call'];
    $u->prepare_path = [FastconPreparePath::class, 'call'];
    $u->prepare_query = [FastconPrepareQuery::class, 'call'];
    $u->graphql_body = [FastconGraphql::class, 'body'];
    $u->graphql_errors = [FastconGraphql::class, 'errors'];
    $u->result_basic = [FastconResultBasic::class, 'call'];
    $u->result_body = [FastconResultBody::class, 'call'];
    $u->result_headers = [FastconResultHeaders::class, 'call'];
    $u->transform_request = [FastconTransformRequest::class, 'call'];
    $u->transform_response = [FastconTransformResponse::class, 'call'];
});
